"""Shared signature-challenge ceremony entry point for the twelve WP-05 QMS modules (SG-138, engineering
half). Generalizes the reference pattern already proven by every other signing module in this codebase
(see e.g. app/modules/batch/router.py's own `POST /{batch_id}/signature-challenges`): resolve the
Document 106 policy for a (record_type, action) pair, load the record, create a challenge bound to it,
and return the receipt the client presents back to the module's own mutating command.

Every one of the twelve QMS command files' own private `_record_hash()` helper is byte-identical --
`sha256_hex({"id": str(record.id), "version": record.version})` -- so one implementation here replaces
twelve near-duplicate copies for this one purpose. Nothing about resolve/consume/sign itself changes;
this module only adds the missing "obtain a challenge_id" step each router was missing.

Deliberately does NOT seed Document 106 policy rows, and does not invent a `meaning`, signer role,
independence flag or reason-required flag for any (record_type, action) pair -- `meaning` is read
verbatim from the resolved SignaturePolicy row, exactly as every reference implementation does.
`resolve_signature_requirement()` still raises SignaturePolicyUnresolvedError (surfaced as
SIGNATURE_POLICY_UNRESOLVED) when no policy row exists, which is the correct, evidenced behaviour for
every one of the 26 pairs this gap describes until Head of Quality + Regulatory Affairs supply the rows
-- see docs/generated/18_SPEC_GAPS.md SG-138.
"""

import uuid

from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.signature.service import (
    create_challenge,
    enforce_signer_policy,  # noqa: F401 -- re-exported: the 12 QMS command modules import it from here
    resolve_signature_requirement,
)
from app.mutation.errors import ValidationFailedError
from app.mutation.hashing import sha256_hex


class SignatureChallengeRequest(BaseModel):
    action: str


def record_hash(record) -> str:
    """Identical to every QMS command file's own private `_record_hash()` -- (id, version) is the whole
    binding surface a signature challenge needs (SIG-FR-012/013/014 equivalent: the challenge is
    invalidated if the record changed since it was issued)."""
    return sha256_hex({"id": str(record.id), "version": record.version})


async def _resolve_and_challenge(
    session: AsyncSession,
    *,
    actor_user_id: uuid.UUID,
    record_type: str,
    record_id: uuid.UUID,
    record_version: int,
    record_hash_value: str,
    action: str,
    allowed_actions: tuple[str, ...],
) -> dict:
    if action not in allowed_actions:
        raise ValidationFailedError("Unknown action", action=action, allowed=list(allowed_actions))
    policy = await resolve_signature_requirement(session, record_type=record_type, action=action)
    challenge = await create_challenge(
        session,
        user_id=actor_user_id,
        record_type=record_type,
        record_id=record_id,
        record_version=record_version,
        record_hash=record_hash_value,
        meaning=policy.meaning,
    )
    return {
        "challenge_id": str(challenge.id),
        "meaning": challenge.meaning,
        "expires_at": challenge.expires_at.isoformat(),
    }


async def create_qms_signature_challenge(
    session: AsyncSession,
    *,
    actor_user_id: uuid.UUID,
    record_type: str,
    record,
    action: str,
    allowed_actions: tuple[str, ...],
) -> dict:
    """Resolve Document 106 policy for `(record_type, action)`, then create a challenge bound to `record`.

    `allowed_actions` is the caller's own fixed action list for its resource (mirrors the explicit
    `if body.action not in (...)` checks every reference implementation uses) -- an unrecognized action
    is a plain 400, not a policy lookup, so a typo doesn't get reported as a signature-policy gap.
    """
    return await _resolve_and_challenge(
        session, actor_user_id=actor_user_id, record_type=record_type, record_id=record.id,
        record_version=record.version, record_hash_value=record_hash(record), action=action,
        allowed_actions=allowed_actions,
    )


async def create_qms_signature_challenge_for_new_record(
    session: AsyncSession,
    *,
    actor_user_id: uuid.UUID,
    record_type: str,
    record_id: uuid.UUID,
    action: str,
    allowed_actions: tuple[str, ...],
) -> dict:
    """Same ceremony as `create_qms_signature_challenge()`, for the one case in this codebase where the
    signed action itself is `create`: the record does not exist yet at challenge time, so there is no
    `record` object to read `.id`/`.version` from. `record_id` is generated by the caller (server-side,
    e.g. `uuid.uuid4()`) *before* calling this function; the challenge is bound to that id at version 1
    -- the version every new row in this codebase starts at (`version: Mapped[int] = mapped_column(...,
    default=1)`). The caller's own create command must then insert its new row using that exact same id,
    so the row that gets flushed matches the (id, version=1) pair the challenge was issued against --
    `consume_challenge()`'s existing version/hash check does the rest, unchanged.

    Discovered and documented as a genuine defect in SG-138 (training_assignment/create): see
    app/modules/qms/training_router.py's own signature-challenges endpoint for the reference caller.
    """
    return await _resolve_and_challenge(
        session, actor_user_id=actor_user_id, record_type=record_type, record_id=record_id,
        record_version=1, record_hash_value=sha256_hex({"id": str(record_id), "version": 1}), action=action,
        allowed_actions=allowed_actions,
    )
