"""0003_materials_and_qc

Revision ID: 3d221863a71e
Revises: 329495c9e651
Create Date: 2026-08-21 12:21:16.111606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d221863a71e'
down_revision: Union[str, Sequence[str], None] = '329495c9e651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['iam.sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code'),
    schema='materials'
    )
    op.create_table('material_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('supplier_lot', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_lot', sa.String(length=100), nullable=True),
    sa.Column('internal_lot', sa.String(length=100), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('retest_date', sa.Date(), nullable=True),
    sa.Column('received_by_user_id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.materials.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['iam.users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['iam.sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_lot'),
    schema='materials'
    )
    op.create_table('material_lot_dispositions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_lot_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=False),
    sa.Column('disposed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('disposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disposed_by_user_id'], ['iam.users.id'], ),
    sa.ForeignKeyConstraint(['material_lot_id'], ['materials.material_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='materials'
    )
    op.create_table('material_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_lot_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('batch_step_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ebmr.batches.id'], ),
    sa.ForeignKeyConstraint(['batch_step_id'], ['ebmr.batch_steps.id'], ),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['iam.users.id'], ),
    sa.ForeignKeyConstraint(['material_lot_id'], ['materials.material_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='materials'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_issues', schema='materials')
    op.drop_table('material_lot_dispositions', schema='materials')
    op.drop_table('material_lots', schema='materials')
    op.drop_table('materials', schema='materials')
    # ### end Alembic commands ###
