"""0001_initial_kernel_and_ebmr_schema

Revision ID: d462ab05fac3
Revises: 
Create Date: 2026-08-21 10:13:39.296128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd462ab05fac3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='iam'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='iam'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='iam'
    )
    op.create_table('command_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('command_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('expected_version', sa.Integer(), nullable=True),
    sa.Column('resulting_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='mutation'
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mutation'
    )
    op.create_table('vault_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('canonical_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_signature_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'business_id', 'version'),
    schema='vault'
    )
    op.create_table('qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('qualification_code', sa.String(length=100), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['iam.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='iam'
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['iam.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='iam'
    )
    op.create_table('sod_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_a_id', sa.UUID(), nullable=False),
    sa.Column('role_b_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['role_a_id'], ['iam.roles.id'], ),
    sa.ForeignKeyConstraint(['role_b_id'], ['iam.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='iam'
    )
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('command_hash', sa.String(length=64), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['mutation.command_receipts.id'], ),
    sa.PrimaryKeyConstraint('idempotency_key'),
    schema='mutation'
    )
    op.create_table('signature_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce'),
    schema='signature'
    )
    op.create_table('signature_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('required_role_id', sa.UUID(), nullable=True),
    sa.Column('requires_independent_signer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['required_role_id'], ['iam.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_type', 'action'),
    schema='signature'
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['iam.sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code'),
    schema='ebmr'
    )
    op.create_table('user_site_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['iam.roles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['iam.sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', 'role_id'),
    schema='iam'
    )
    op.create_table('signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['signature.signature_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='signature'
    )
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ebmr.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version'),
    schema='ebmr'
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('recipe_version', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('target_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ebmr.products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['ebmr.recipes.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['iam.sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number'),
    schema='ebmr'
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.String(length=4000), nullable=True),
    sa.Column('requires_signature', sa.Boolean(), nullable=False),
    sa.Column('signature_meaning', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['ebmr.recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'step_number'),
    schema='ebmr'
    )
    op.create_table('batch_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('released_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('signature_id', sa.UUID(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ebmr.batches.id'], ),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ebmr'
    )
    op.create_table('batch_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ebmr.batches.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ebmr'
    )
    op.create_table('batch_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('recipe_step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ebmr.batches.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['iam.users.id'], ),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['ebmr.recipe_steps.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['iam.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'recipe_step_id'),
    schema='ebmr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_steps', schema='ebmr')
    op.drop_table('batch_reviews', schema='ebmr')
    op.drop_table('batch_releases', schema='ebmr')
    op.drop_table('recipe_steps', schema='ebmr')
    op.drop_table('batches', schema='ebmr')
    op.drop_table('recipes', schema='ebmr')
    op.drop_table('signatures', schema='signature')
    op.drop_table('user_site_roles', schema='iam')
    op.drop_table('products', schema='ebmr')
    op.drop_table('signature_policies', schema='signature')
    op.drop_table('signature_challenges', schema='signature')
    op.drop_table('idempotency_keys', schema='mutation')
    op.drop_table('sod_rules', schema='iam')
    op.drop_table('sites', schema='iam')
    op.drop_table('qualifications', schema='iam')
    op.drop_table('vault_versions', schema='vault')
    op.drop_table('outbox_events', schema='mutation')
    op.drop_table('command_receipts', schema='mutation')
    op.drop_table('users', schema='iam')
    op.drop_table('roles', schema='iam')
    op.drop_table('organizations', schema='iam')
    op.drop_table('audit_events', schema='audit')
    # ### end Alembic commands ###
