"""Import every module's models so Base.metadata is complete for Alembic autogenerate."""

from app.core.db import Base
from app.modules.ai_governance import models as ai_governance_models  # noqa: F401
from app.modules.audit import models as audit_models  # noqa: F401
from app.modules.batch import models as batch_models  # noqa: F401
from app.modules.batch_execution import models as batch_execution_models  # noqa: F401
from app.modules.dataops import models as dataops_models  # noqa: F401
from app.modules.ddcp import models as ddcp_models  # noqa: F401
from app.modules.deployment import models as deployment_models  # noqa: F401
from app.modules.device import models as device_models  # noqa: F401
from app.modules.disaster_recovery import models as disaster_recovery_models  # noqa: F401
from app.modules.edge import models as edge_models  # noqa: F401
from app.modules.equipment import aseptic_models as equipment_aseptic_models  # noqa: F401
from app.modules.equipment import cleaning_models as equipment_cleaning_models  # noqa: F401
from app.modules.equipment import em_models as equipment_em_models  # noqa: F401
from app.modules.equipment import models as equipment_models  # noqa: F401
from app.modules.equipment import sterilization_models as equipment_sterilization_models  # noqa: F401
from app.modules.erp import models as erp_models  # noqa: F401
from app.modules.eventbus import models as eventbus_models  # noqa: F401
from app.modules.evidence import models as evidence_models  # noqa: F401
from app.modules.genealogy import models as genealogy_models  # noqa: F401
from app.modules.iam import models as iam_models  # noqa: F401
from app.modules.lims_integration import models as lims_integration_models  # noqa: F401
from app.modules.machine_integration import models as machine_integration_models  # noqa: F401
from app.modules.material import models as material_models  # noqa: F401
from app.modules.material_specification import models as material_specification_models  # noqa: F401
from app.modules.mutation import models as mutation_models  # noqa: F401
from app.modules.packaging import models as packaging_models  # noqa: F401
from app.modules.postmarket import models as postmarket_models  # noqa: F401
from app.modules.postmarket import obligation_models as postmarket_obligation_models  # noqa: F401
from app.modules.postmarket import reportability_models as postmarket_reportability_models  # noqa: F401
from app.modules.product import models as product_models  # noqa: F401
from app.modules.product_master import models as product_master_models  # noqa: F401
from app.modules.qa_review import models as qa_review_models  # noqa: F401
from app.modules.qc import models as qc_models  # noqa: F401
from app.modules.qms import capa_models as qms_capa_models  # noqa: F401
from app.modules.qms import change_models as qms_change_models  # noqa: F401
from app.modules.qms import complaint_models as qms_complaint_models  # noqa: F401
from app.modules.qms import document_models as qms_document_models  # noqa: F401
from app.modules.qms import field_action_models as qms_field_action_models  # noqa: F401
from app.modules.qms import internal_audit_models as qms_internal_audit_models  # noqa: F401
from app.modules.qms import models as qms_models  # noqa: F401
from app.modules.qms import ncr_models as qms_ncr_models  # noqa: F401
from app.modules.qms import quality_metrics_models as qms_quality_metrics_models  # noqa: F401
from app.modules.qms import risk_models as qms_risk_models  # noqa: F401
from app.modules.qms import scar_models as qms_scar_models  # noqa: F401
from app.modules.qms import training_models as qms_training_models  # noqa: F401
from app.modules.readmodels import models as readmodels_models  # noqa: F401
from app.modules.recipe import models as recipe_models  # noqa: F401
from app.modules.recipe_master import models as recipe_master_models  # noqa: F401
from app.modules.release import models as release_models  # noqa: F401
from app.modules.rules import models as rules_models  # noqa: F401
from app.modules.security import appsec_models as security_appsec_models  # noqa: F401
from app.modules.security import crypto_models as security_crypto_models  # noqa: F401
from app.modules.security import identity_models as security_identity_models  # noqa: F401
from app.modules.security import incident_models as security_incident_models  # noqa: F401
from app.modules.security import models as security_models  # noqa: F401
from app.modules.security import netzero_models as security_netzero_models  # noqa: F401
from app.modules.security import privileged_access_models as security_privileged_access_models  # noqa: F401
from app.modules.security import supplychain_models as security_supplychain_models  # noqa: F401
from app.modules.signature import models as signature_models  # noqa: F401
from app.modules.sre import models as sre_models  # noqa: F401
from app.modules.supplier_quality import models as supplier_quality_models  # noqa: F401
from app.modules.validation import models as validation_models  # noqa: F401
from app.modules.validation import models_wp14 as validation_models_wp14  # noqa: F401
from app.modules.vault import models as vault_models  # noqa: F401
from app.modules.yield_reconciliation import models as yield_reconciliation_models  # noqa: F401

metadata = Base.metadata
