"""Document 13 (SPEC-EBMR-004) — Genealogy & Traceability Engine. New module. See migration
<pending>_0014_genealogy_schema for the schema deviations from docs/generated/04_DATA_MODEL_CATALOGUE.md.

Both owned entities (`genealogy_node`, `genealogy_edge`) are DDL-ready -- the best ratio of any module
built so far. Per Document 13 §8 ("Write Path"), genealogy rows are meant to be generated by domain events
(MaterialConsumed, DrugBatchProduced, DeviceComponentAssembled, FillLinkedToDevice, PackagingCompleted,
DistributionLinked) from other modules, not by a public write API -- there is no POST /genealogy/v1/nodes
or /edges endpoint in the document's own 8-API list. None of those named events exist yet: Material
Service is WP-04 (not built), and batch_execution/device (Documents 11/12) emit differently-named events
(BatchIssued, DeviceUnitCreated, ...) that don't map onto them. This pass therefore builds the graph
engine itself (node/edge creation, correction, consistency/cycle rules, traversal queries) as internal
service functions with no public write endpoint -- exactly matching the document's own exposure boundary
-- and leaves real event-driven population for whenever those producers exist (SG-052). The 5 read-only
query APIs are built and exposed. `POST /genealogy/v1/impact-assessments` and `POST /genealogy/v1/exports`
have no backing entity anywhere in the data model catalogue (only 2 entities are owned by this module) --
deferred (SG-051).
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import ForeignKey, Numeric, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.core.db import Base

# GEN-FR-001: the node types named across Document 13 §2's graph model and §3's requirement text.
NODE_TYPES = (
    "supplier_lot",
    "material_lot",
    "material_container",
    "drug_batch",
    "intermediate",
    "fill_group",
    "device_component_lot",
    "device_component_serial",
    "device_unit",
    "combination_product_lot",
    "combination_product_serial",
    "package",
    "carton",
    "pallet",
    "distribution_reference",
    "evidence_record",
    "constituent_compatibility_version",
)

# GEN-FR-002: Document 13 §5's authoritative controlled edge-type catalogue (the source document's own
# table, not the illustrative examples in the requirement-table prose, which name a couple of synonyms
# -- CONTAINS/TESTED_BY -- that §5 doesn't actually include).
EDGE_TYPES = (
    "RECEIVED_AS",
    "SPLIT_FROM",
    "DERIVED_FROM",
    "CONSUMED_IN",
    "PRODUCED_AS",
    "FILLED_INTO",
    "ASSEMBLED_INTO",
    "PACKAGED_AS",
    "AGGREGATED_INTO",
    "STERILIZED_IN",
    "REWORKED_FROM",
    "SUPERSEDES",
    "DISTRIBUTED_AS",
)

# GEN-FR-024: rework/correction relationships are separately typed precisely so cycle detection over
# normal ancestry can ignore them -- REWORKED_FROM/SUPERSEDES legitimately point backward without
# implying an ancestry cycle.
ANCESTRY_EDGE_TYPES = tuple(t for t in EDGE_TYPES if t not in ("REWORKED_FROM", "SUPERSEDES"))

EDGE_STATES = ("ACTIVE", "SUPERSEDED", "VOIDED")


class GenealogyNode(Base):
    """No `version`/`state` column in the source DDL -- nodes are pure insert-only facts (GEN-FR-016);
    only edges are ever superseded (GEN-FR-017)."""

    __tablename__ = "genealogy_node"
    __table_args__ = {"schema": "ebmr"}

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    site_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("iam.sites.id"), nullable=False)
    node_type: Mapped[str] = mapped_column(String(60), nullable=False)
    business_ref: Mapped[str | None] = mapped_column(String(200))
    authoritative_record_type: Mapped[str | None] = mapped_column(String(80))
    authoritative_record_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    authoritative_version: Mapped[int | None] = mapped_column()
    record_hash: Mapped[str | None] = mapped_column(String(64))
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())


class GenealogyEdge(Base):
    __tablename__ = "genealogy_edge"
    __table_args__ = (
        UniqueConstraint("from_node_id", "to_node_id", "edge_type", "source_event_id"),
        {"schema": "ebmr"},
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    from_node_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("ebmr.genealogy_node.id"), nullable=False)
    to_node_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("ebmr.genealogy_node.id"), nullable=False)
    edge_type: Mapped[str] = mapped_column(String(60), nullable=False)
    quantity: Mapped[Decimal | None] = mapped_column(Numeric(24, 8))
    uom: Mapped[str | None] = mapped_column(String(40))
    # SG-146 (remainder, module 4 of 8), MIG-FR-004 expand step: dual-written best-effort, backfillable
    # (ebmr.genealogy_edge is mutable — UPDATE granted, migration 5e23e1067790 0014).
    uom_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("rules.gxp_uom.uom_id"))
    step_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    source_event_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    state: Mapped[str] = mapped_column(String(30), nullable=False, default="ACTIVE")
    supersedes_edge_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("ebmr.genealogy_edge.id"))
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
