"""Shared signature-challenge ceremony entry point for the WP-12/WP-14 validation platform (Documents
79-96, resolved as the validation counterpart of SG-138). Same reasoning as
`app/modules/qms/signature_support.py` -- generalizes the reference pattern already proven by
`app/modules/batch/router.py`'s own `POST /{batch_id}/signature-challenges`: resolve the Document 106
policy for a `(record_type, action)` pair, create a challenge bound to the record, and return the
receipt the client presents back to the module's own signed mutating command.

Two shapes exist in this module, both already anticipated by the command layer itself:

* **Existing-record actions** (approve/release/triage/disposition/.../deployment_check) -- the record
  already exists; the challenge binds to its real `(id, version)` via
  `app.modules.validation.shared.record_hash()`, exactly what
  `app.modules.validation.shared.verify_reauth_and_consume()` expects on the consuming side.
* **Signed-CREATE actions** (`validation_exception.create`, `periodic_validation_review.create`,
  `performance_qualification_scenario.create`, `performance_run.create`) -- the row does not exist yet
  at challenge time. Every one of these command classes already carries an optional `new_record_id`
  field for exactly this reason (see each command's own docstring, e.g.
  `commands_performance.py::create_performance_scenario`): the caller pre-generates the id here, the
  challenge is bound to `(id, version=1)`, and the caller's create command inserts its new row using
  that same id so the two match. This is the identical shape
  `app.modules.qms.signature_support.create_qms_signature_challenge_for_new_record()` already
  established for `training_assignment.create` (SG-138).

`validated_release_authorization.authorize` is the one outlier -- it binds to a hash of the full
command payload rather than a record id (see `commands_vsr.py::_apply_signature_for_create` /
`create_challenge_hash()`), because Document 106 row 166 signs the authorization decision itself, not
a placeholder row. That endpoint is implemented directly in `router_wp14.py` against those exact
functions rather than through this generic helper.

Deliberately does NOT seed Document 106 policy rows, and does not invent a `meaning`, signer role,
independence flag or reason-required flag for any `(record_type, action)` pair -- `meaning` is read
verbatim from the resolved `SignaturePolicy` row. `resolve_signature_requirement()` still raises
`SignaturePolicyUnresolvedError` (surfaced as `SIGNATURE_POLICY_UNRESOLVED`) when no policy row exists,
which is the correct, evidenced behaviour for every one of these pairs until Head of Quality +
Regulatory Affairs supply Document 106 rows -- see `docs/generated/18_SPEC_GAPS.md`.
"""

import uuid

from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.signature.service import create_challenge
from app.modules.validation.shared import record_hash, resolve_signature
from app.mutation.errors import ValidationFailedError


class SignatureChallengeRequest(BaseModel):
    action: str


async def _resolve_and_challenge(
    session: AsyncSession, *, actor_user_id: uuid.UUID, record_type: str, record_id: uuid.UUID,
    record_version: int, record_hash_value: str, action: str, allowed_actions: tuple[str, ...],
) -> dict:
    if action not in allowed_actions:
        raise ValidationFailedError("Unknown action", action=action, allowed=list(allowed_actions))
    policy = await resolve_signature(session, record_type=record_type, action=action)
    challenge = await create_challenge(
        session, user_id=actor_user_id, record_type=record_type, record_id=record_id,
        record_version=record_version, record_hash=record_hash_value, meaning=policy.meaning,
    )
    return {
        "challenge_id": str(challenge.id), "meaning": challenge.meaning,
        "expires_at": challenge.expires_at.isoformat(),
    }


async def create_validation_signature_challenge(
    session: AsyncSession, *, actor_user_id: uuid.UUID, record_type: str, record, action: str,
    allowed_actions: tuple[str, ...],
) -> dict:
    """Challenge bound to an existing record's real `(id, version)`."""
    return await _resolve_and_challenge(
        session, actor_user_id=actor_user_id, record_type=record_type, record_id=record.id,
        record_version=record.version, record_hash_value=record_hash(record.id, record.version),
        action=action, allowed_actions=allowed_actions,
    )


async def create_validation_signature_challenge_for_new_record(
    session: AsyncSession, *, actor_user_id: uuid.UUID, record_type: str, record_id: uuid.UUID, action: str,
    allowed_actions: tuple[str, ...],
) -> dict:
    """Challenge bound to `(record_id, version=1)` for a row that does not exist yet -- `record_id` is
    generated by the caller (`uuid.uuid4()`) before calling this, then handed back to the client as the
    command's `new_record_id`. See module docstring."""
    return await _resolve_and_challenge(
        session, actor_user_id=actor_user_id, record_type=record_type, record_id=record_id,
        record_version=1, record_hash_value=record_hash(record_id, 1), action=action,
        allowed_actions=allowed_actions,
    )
