dbfilename redis_cache.rdb
dir /home/hepin/mydata/eBMR-new/config/pids
pidfile /home/hepin/mydata/eBMR-new/config/pids/redis_cache.pid
bind 127.0.0.1
port 13001
maxmemory 780mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/hepin/mydata/eBMR-new/config/redis_cache.acl
