dbfilename redis_queue.rdb
dir /home/hepin/mydata/eBMR-new/config/pids
pidfile /home/hepin/mydata/eBMR-new/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /home/hepin/mydata/eBMR-new/config/redis_queue.acl
